"""Deterministic, history-aware workout planner. No randomness — given the same
inputs it always produces the same plan, which makes it fully testable and a
reliable safety net when no LLM is available.
"""

from collections import Counter

from app.planner.base import equipment_allowed, scheme_for
from app.planner.context import CoachContext
from app.schemas import (
    CatalogExercise,
    PlanItem,
    PlanRequest,
    WorkoutDay,
    WorkoutPlan,
)

_MINUTES_PER_EXERCISE = 12


def _items_per_day(session_minutes: int) -> int:
    return max(2, min(6, session_minutes // _MINUTES_PER_EXERCISE))


def _candidate_pool(
    request: PlanRequest,
    catalog: list[CatalogExercise],
    context: CoachContext,
) -> list[CatalogExercise]:
    available = [e.value for e in request.available_equipment]
    avoid = set(request.avoid_exercise_ids)
    target = {m.value for m in request.target_muscles}
    recently_used = set(context.recently_used_exercise_ids)

    pool = [
        ex
        for ex in catalog
        if ex.id not in avoid and equipment_allowed(ex, available)
    ]

    def score(ex: CatalogExercise) -> tuple[float, int]:
        s = 0.0
        if target:
            # Prioritize exercises that hit the requested muscles.
            if not target.intersection(ex.primary_muscles):
                s += 100
        else:
            # Prefer under-trained muscles (lower recent volume ranks first).
            volumes = [context.volume_by_muscle.get(m, 0.0) for m in ex.primary_muscles]
            s += min(volumes) if volumes else 0.0
        # Deweight (but don't exclude) exercises used recently.
        if ex.id in recently_used:
            s += 50
        return (s, ex.id)

    return sorted(pool, key=score)


def _day_focus(items: list[PlanItem], by_id: dict[int, CatalogExercise]) -> str:
    muscles = Counter()
    for item in items:
        for muscle in by_id[item.exercise_id].primary_muscles:
            muscles[muscle] += 1
    if not muscles:
        return "Full body"
    top, _ = muscles.most_common(1)[0]
    return f"{top.title()} focus"


class FallbackPlanner:
    name = "fallback"

    def generate(
        self,
        request: PlanRequest,
        catalog: list[CatalogExercise],
        context: CoachContext,
    ) -> WorkoutPlan:
        by_id = {ex.id: ex for ex in catalog}
        pool = _candidate_pool(request, catalog, context)
        per_day = _items_per_day(request.session_minutes)
        sets, reps, rest = scheme_for(request.goal.value, request.experience.value)
        recently_used = set(context.recently_used_exercise_ids)

        # Take enough exercises to fill the week, cycling the pool if it's small.
        needed = per_day * request.days_per_week
        chosen: list[CatalogExercise] = []
        i = 0
        while pool and len(chosen) < needed:
            chosen.append(pool[i % len(pool)])
            i += 1

        # Round-robin into days so muscle groups spread across the week.
        days_items: list[list[PlanItem]] = [[] for _ in range(request.days_per_week)]
        for index, ex in enumerate(chosen):
            rationale = None
            if ex.id in recently_used:
                rationale = "Used recently — kept light / lower priority."
            elif not request.target_muscles:
                rationale = "Adds volume to an under-trained muscle group."
            days_items[index % request.days_per_week].append(
                PlanItem(
                    exercise_id=ex.id,
                    exercise_name=ex.name,
                    sets=sets,
                    reps=reps,
                    rest_seconds=rest,
                    rationale=rationale,
                )
            )

        days = [
            WorkoutDay(focus=_day_focus(items, by_id), items=items)
            for items in days_items
            if items
        ]

        return WorkoutPlan(
            goal=request.goal,
            days_per_week=request.days_per_week,
            days=days,
            insights=context.insights,
            generated_by=self.name,
            notes="Generated by the deterministic fallback planner.",
        )
